#
# Jekyll configuration
#

# Handling reading
exclude:
  - "bower_components"
  - "bower.json"
  - "examples"
  - "node_modules"
  - "package.json"
  - "Gruntfile.js"
  - "LICENSE.md"
  - "README.md"

# Serving
host:             127.0.0.1
port:             9001

# Outputting
permalink:        pretty

# Custom vars
# TBD
