# Handling Reading
exclude:
  - "bower_components"
  - "bower.json"
  - "node_modules"
  - "package.json"
  - "Gruntfile.js"

# Serving
host:             127.0.0.1
port:             9001

# Outputting
permalink:        pretty

# Custom vars
bootstrap_version:  4.0.0-alpha.2

cdn:
  jquery:         https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js
